### PR TITLE
Add missing legacy plugins page, workflow overview bugfixes.

### PR DESCRIPTION
**Pull request by leamas**
The workflow overview contains some ascii art which is plain
wrong. Drop for now, and enhance/cleanuo some wordings.

Add missing page on legacy plugins.

### CODE REVIEW

**Comment by rgleason** [comment]
I just did revision on legacy, also both shipdriver and testplugin have been updated.

**Comment by leamas** [comment]
But you didn't puish, did you ?

**Comment by leamas** [comment]
BTW: By keeping the usual max 80 char/line limitation, patches and tools works much better. Is this something you can do?

**Comment by rgleason** [comment]
No I didn't race to push. But have now.

BTW My reading of antora/asciidoc  yielded the recommended technique of keep one sentence per line as the best way.  So I have not done tbat.

**Comment by rgleason** [comment]
So what is wrong with the diagram?  The metadata is sent to cloudsmith then transferred to ocpn/plugins by the PI Dev.

**Comment by rgleason** [comment]
BTW I resolved the conflict and merged

**Comment by leamas** [comment]
It's plain wrong for two reason (quite a lot, given four possibilities)

  - CircleCI is not the only builder
  - Metadata does not flow through cloudsmith in the shipdriver workflow, only in testplugin.

**Comment by leamas** [comment]
We need to talk more about this when you have reached the point "code completed" i. e., that everything you intend to write is in place. I am there, the raw text is completed.

At this point we can start the review phase.

**Comment by leamas** [comment]
> BTW I resolved the conflict and merged

yes. But when doing so, you removed all linkage from nav.adoc to legacy-plugins.adoc, effectively making that file invisible. I know, such things do happen when rebasing, it's not always trivial.  But I would appreciate if you added a link to legacy-plugins.adoc in nav.adoc

**Comment by rgleason** [comment]
Not really, I changed its level.

**Comment by leamas** [comment]
> Not really, I changed its level.

Perhaps you was to tired:

    $ git grep legacy-plugins.adoc | grep xref
    $

i. e., there are no links whatsoever, anywhere, to legacy-plugins.adoc.

But never mind, this is just a small nit-pick.  Let's talk in zulip until we can come down to specific remarks and PRs.

**Comment by rgleason** [comment]
I do not have legacy-plugins.adoc anywhere so why would I have a link?

**Comment by rgleason** [comment]
Also developer guide has two bad links

**Comment by rgleason** [comment]
I found those docs and can fix them now.

**Comment by leamas** [comment]
> Also developer guide has two bad links

I don't push anything, I make PRs which you merge. OTOH, of course a PR of mine could be broken, remember I make them against rgleason/ocpn-dev-manual which might be out of sync with your local copy.

The problem with the 'internationalization' link is that the file has been renamed, it's now i18n.adoc, and the link should be updated accordingly. The 'internationalization.adoc' document has been, and should still be dropped.

likewise, modular_packaging has been moved to cmake.adoc, where it covers tthe complete cmake setup. It's the link which is wrong and should be updated, the modular_packaging document is dropped and should not be  resurrected.

**Comment by leamas** [comment]
> I do not have legacy-plugins.adoc anywhere so why would I have a link?

Yes, you have that:

    $ git rev-parse --short HEAD
    5d62340
    $ git rev-parse --short upstream/main
    5d62340
    $ ls modules/ROOT/pages/legacy-plugins.adoc 
    modules/ROOT/pages/legacy-plugins.adoc

I. e., the commit 5d62340, the current tip of rgleason/ocpn-dev-manual contains that file

**Pull request merged**
